version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Extracting Confluent credentials from Secrets Manager JSON"
      - export CONFLUENT_API_KEY=$(echo $CONFLUENT_CREDS | jq -r '.api_key')
      - export CONFLUENT_API_SECRET=$(echo $CONFLUENT_CREDS | jq -r '.api_secret')
      - export KAFKA_CLUSTER=$(echo $CONFLUENT_CREDS | jq -r '.kafka_cluster')
      - echo "Generating Terraform files dynamically"
      - chmod +x scripts/generate_tf.sh
      - ./scripts/generate_tf.sh
      - cd tf
      - terraform init -input=false
      - |
        terraform apply -auto-approve -input=false \
          -var="confluent_api_key=$CONFLUENT_API_KEY" \
          -var="confluent_api_secret=$CONFLUENT_API_SECRET" \
          -var="kafka_cluster=$KAFKA_CLUSTER"


