---
version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - >
        curl -o terraform.zip
        https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform -version

  build:
    commands:
      - echo "Running Terraform apply in $(pwd)"
      - echo "Extracting Confluent credentials from Secrets Manager JSON"
      - >
        export CONFLUENT_API_KEY=$(echo $CONFLUENT_CREDS |
        jq -r '.api_key')
      - >
        export CONFLUENT_API_SECRET=$(echo $CONFLUENT_CREDS |
        jq -r '.api_secret')
      - mkdir -p tf
      - >
        METADATA_FILE=$(find requests -name metadata.json | head -n 1)
      - >
        TOPIC_NAME=$(jq -r '.topic_name' $METADATA_FILE)
      - >
        PARTITIONS=$(jq -r '.partitions' $METADATA_FILE)
      - >
        DESCRIPTION=$(jq -r '.description' $METADATA_FILE)
      - >
        cat > tf/main.tf <<EOF
        terraform {
          required_providers {
            confluent = {
              source  = "confluentinc/confluent"
              version = "2.5.0"
            }
          }
        }

        provider "confluent" {
          cloud_api_key    = var.confluent_api_key
          cloud_api_secret = var.confluent_api_secret
        }

        resource "confluent_kafka_topic" "topic" {
          kafka_cluster {
            id = var.kafka_cluster
          }
          topic_name       = "$TOPIC_NAME"
          partitions_count = $PARTITIONS
          config = {
            "cleanup.policy" = "delete"
          }
          rest_endpoint = "https://api.confluent.cloud"
        }

        variable "confluent_api_key" {}
        variable "confluent_api_secret" {}
        variable "kafka_cluster" {}
        EOF
      - cd tf
      - terraform init -input=false
      - >
        terraform apply -auto-approve -input=false
        -var="confluent_api_key=$CONFLUENT_API_KEY"
        -var="confluent_api_secret=$CONFLUENT_API_SECRET"

artifacts:
  files:
    - "**/*"
